### ISSUE TITLE
Being able to create a point on the map manually

### ISSUE THREAD

**Issue by uSyzex** [penguin86/nextcloud-maps-client#11]
Hi,

For what I understand, we can only create from our own position at a moment. It would super useless to be able to select by ourselves a point on the map to create the Geopoint !

Another idea: Being able to import geo point from others apps through Share:
Being on Google Maps --> Select point --> Share --> Create Geopoint in Geobookmarks

These are only enhancements, your app is already super useful thank you very much !

Regards

**Comment by penguin86** [comment]
Hi @uSyzex ,
the ability to create a geobookmark "manually" from the map **will be added** in a future version (I hope to work on it during the Christmas vacations).

Creating a geobookmark from another app, btw, is already supported via the ["geo: uri" standard:](https://en.m.wikipedia.org/wiki/Geo_URI_scheme).
To test it, try [clicking on this link](geo:37.786971,-122.399677), or sharing from another app supporting geo uri, i.e. OsmAnd. This is the official standard defined by the [IETF](https://en.m.wikipedia.org/wiki/Internet_Engineering_Task_Force).

For some reason Google Maps implements this format only when receiving a share, and not when sharing. I suspect this is to keep users from leaving Google Maps, as the are not trackable otherwise.
If you try to share from google maps, you may notice the shared content contains an URL like this: "https://maps.app.goo.gl/RVamtGrXLhyJJVp67". This URL doesn't contain clear GPS coordinates, and, as I could understand (but may be wrong), it needs a call to Google's webservice to be "decoded". This would not be appropriate, because allows user tracking and would trigger an anti-feature for this app on F-Droid.
BTW, I'll study the topic and see if there is any workaround. If you are aware of any open source able to decode google maps shared positions, please report it below, so I can look at the source ad understand how the URL is decoded.

As a temporary workaround, I suggest installing OsmAnd and sharing the location from there selecting "osm:" as format.

Thanks for writing!
Regards

**Comment by penguin86** [comment]
Available in v0.3.4
