### ISSUE TITLE
Tile view

### ISSUE THREAD

**Issue by Valdnet** [penguin86/nextcloud-maps-client#5]
When you view the tile, you can see a bit of the date, which is redundant.

![obraz](https://user-images.githubusercontent.com/47037905/138559982-e6091742-cb61-4e7b-947f-e18547b21394.png)

App:
Nextcloud Maps Geobookmarks v0.3.3

**Comment by penguin86** [comment]
Hello Valdnet, thanks for reporting.
The tile view was present because I started from the Nextcloud SSO example project and didn't remove it. It does not make a lot of sense, so I removed the button from the current release and will be replaced by the map view button in a future release.
So I'm closing this ticket.

Thank you, have a nice day
Daniele
